// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v4.23.2
// source: bili.proto

package bili

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// BiliRpcServiceClient is the client API for BiliRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BiliRpcServiceClient interface {
	RoomCanUseServer(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc_go.CallOption) (*wrapperspb.BoolValue, common.ErrorWithAttachment)
}

type biliRpcServiceClient struct {
	cc *triple.TripleConn
}

type BiliRpcServiceClientImpl struct {
	RoomCanUseServer func(ctx context.Context, in *wrapperspb.Int64Value) (*wrapperspb.BoolValue, error)
}

func (c *BiliRpcServiceClientImpl) GetDubboStub(cc *triple.TripleConn) BiliRpcServiceClient {
	return NewBiliRpcServiceClient(cc)
}

func (c *BiliRpcServiceClientImpl) XXX_InterfaceName() string {
	return "BiliRpcService"
}

func NewBiliRpcServiceClient(cc *triple.TripleConn) BiliRpcServiceClient {
	return &biliRpcServiceClient{cc}
}

func (c *biliRpcServiceClient) RoomCanUseServer(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc_go.CallOption) (*wrapperspb.BoolValue, common.ErrorWithAttachment) {
	out := new(wrapperspb.BoolValue)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/RoomCanUseServer", in, out)
}

// BiliRpcServiceServer is the server API for BiliRpcService service.
// All implementations must embed UnimplementedBiliRpcServiceServer
// for forward compatibility
type BiliRpcServiceServer interface {
	RoomCanUseServer(context.Context, *wrapperspb.Int64Value) (*wrapperspb.BoolValue, error)
	mustEmbedUnimplementedBiliRpcServiceServer()
}

// UnimplementedBiliRpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBiliRpcServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedBiliRpcServiceServer) RoomCanUseServer(context.Context, *wrapperspb.Int64Value) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoomCanUseServer not implemented")
}
func (s *UnimplementedBiliRpcServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedBiliRpcServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedBiliRpcServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &BiliRpcService_ServiceDesc
}
func (s *UnimplementedBiliRpcServiceServer) XXX_InterfaceName() string {
	return "BiliRpcService"
}

func (UnimplementedBiliRpcServiceServer) mustEmbedUnimplementedBiliRpcServiceServer() {}

// UnsafeBiliRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BiliRpcServiceServer will
// result in compilation errors.
type UnsafeBiliRpcServiceServer interface {
	mustEmbedUnimplementedBiliRpcServiceServer()
}

func RegisterBiliRpcServiceServer(s grpc_go.ServiceRegistrar, srv BiliRpcServiceServer) {
	s.RegisterService(&BiliRpcService_ServiceDesc, srv)
}

func _BiliRpcService_RoomCanUseServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("RoomCanUseServer", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// BiliRpcService_ServiceDesc is the grpc_go.ServiceDesc for BiliRpcService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var BiliRpcService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "BiliRpcService",
	HandlerType: (*BiliRpcServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "RoomCanUseServer",
			Handler:    _BiliRpcService_RoomCanUseServer_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "bili.proto",
}
