// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: bili.proto

package bili

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BiliRpcService_RoomCanUseServer_FullMethodName = "/BiliRpcService/RoomCanUseServer"
	BiliRpcService_AddNewGuard_FullMethodName      = "/BiliRpcService/AddNewGuard"
)

// BiliRpcServiceClient is the client API for BiliRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BiliRpcServiceClient interface {
	RoomCanUseServer(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
	AddNewGuard(ctx context.Context, in *AddNewGuardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type biliRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBiliRpcServiceClient(cc grpc.ClientConnInterface) BiliRpcServiceClient {
	return &biliRpcServiceClient{cc}
}

func (c *biliRpcServiceClient) RoomCanUseServer(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, BiliRpcService_RoomCanUseServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biliRpcServiceClient) AddNewGuard(ctx context.Context, in *AddNewGuardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BiliRpcService_AddNewGuard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BiliRpcServiceServer is the server API for BiliRpcService service.
// All implementations must embed UnimplementedBiliRpcServiceServer
// for forward compatibility.
type BiliRpcServiceServer interface {
	RoomCanUseServer(context.Context, *wrapperspb.Int64Value) (*wrapperspb.BoolValue, error)
	AddNewGuard(context.Context, *AddNewGuardRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedBiliRpcServiceServer()
}

// UnimplementedBiliRpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBiliRpcServiceServer struct{}

func (UnimplementedBiliRpcServiceServer) RoomCanUseServer(context.Context, *wrapperspb.Int64Value) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoomCanUseServer not implemented")
}
func (UnimplementedBiliRpcServiceServer) AddNewGuard(context.Context, *AddNewGuardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNewGuard not implemented")
}
func (UnimplementedBiliRpcServiceServer) mustEmbedUnimplementedBiliRpcServiceServer() {}
func (UnimplementedBiliRpcServiceServer) testEmbeddedByValue()                        {}

// UnsafeBiliRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BiliRpcServiceServer will
// result in compilation errors.
type UnsafeBiliRpcServiceServer interface {
	mustEmbedUnimplementedBiliRpcServiceServer()
}

func RegisterBiliRpcServiceServer(s grpc.ServiceRegistrar, srv BiliRpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedBiliRpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BiliRpcService_ServiceDesc, srv)
}

func _BiliRpcService_RoomCanUseServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiliRpcServiceServer).RoomCanUseServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BiliRpcService_RoomCanUseServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiliRpcServiceServer).RoomCanUseServer(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiliRpcService_AddNewGuard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNewGuardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiliRpcServiceServer).AddNewGuard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BiliRpcService_AddNewGuard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiliRpcServiceServer).AddNewGuard(ctx, req.(*AddNewGuardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BiliRpcService_ServiceDesc is the grpc.ServiceDesc for BiliRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BiliRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BiliRpcService",
	HandlerType: (*BiliRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RoomCanUseServer",
			Handler:    _BiliRpcService_RoomCanUseServer_Handler,
		},
		{
			MethodName: "AddNewGuard",
			Handler:    _BiliRpcService_AddNewGuard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bili.proto",
}
