// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: bili/bili.proto

package bili

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddNewGuardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	GuardLevel    int32                  `protobuf:"varint,4,opt,name=guardLevel,proto3" json:"guardLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNewGuardRequest) Reset() {
	*x = AddNewGuardRequest{}
	mi := &file_bili_bili_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNewGuardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewGuardRequest) ProtoMessage() {}

func (x *AddNewGuardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bili_bili_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewGuardRequest.ProtoReflect.Descriptor instead.
func (*AddNewGuardRequest) Descriptor() ([]byte, []int) {
	return file_bili_bili_proto_rawDescGZIP(), []int{0}
}

func (x *AddNewGuardRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *AddNewGuardRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AddNewGuardRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddNewGuardRequest) GetGuardLevel() int32 {
	if x != nil {
		return x.GuardLevel
	}
	return 0
}

var File_bili_bili_proto protoreflect.FileDescriptor

const file_bili_bili_proto_rawDesc = "" +
	"\n" +
	"\x0fbili/bili.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"z\n" +
	"\x12AddNewGuardRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x03R\x06roomId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"guardLevel\x18\x04 \x01(\x05R\n" +
	"guardLevel2\x9d\x01\n" +
	"\x0eBiliRpcService\x12M\n" +
	"\x10RoomCanUseServer\x12\x1b.google.protobuf.Int64Value\x1a\x1a.google.protobuf.BoolValue\"\x00\x12<\n" +
	"\vAddNewGuard\x12\x13.AddNewGuardRequest\x1a\x16.google.protobuf.Empty\"\x00B<\n" +
	"\x1acom.htdong.common.rpc.biliB\x13BiliRpcServiceProtoP\x01Z\a./;bilib\x06proto3"

var (
	file_bili_bili_proto_rawDescOnce sync.Once
	file_bili_bili_proto_rawDescData []byte
)

func file_bili_bili_proto_rawDescGZIP() []byte {
	file_bili_bili_proto_rawDescOnce.Do(func() {
		file_bili_bili_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bili_bili_proto_rawDesc), len(file_bili_bili_proto_rawDesc)))
	})
	return file_bili_bili_proto_rawDescData
}

var file_bili_bili_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bili_bili_proto_goTypes = []any{
	(*AddNewGuardRequest)(nil),    // 0: AddNewGuardRequest
	(*wrapperspb.Int64Value)(nil), // 1: google.protobuf.Int64Value
	(*wrapperspb.BoolValue)(nil),  // 2: google.protobuf.BoolValue
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_bili_bili_proto_depIdxs = []int32{
	1, // 0: BiliRpcService.RoomCanUseServer:input_type -> google.protobuf.Int64Value
	0, // 1: BiliRpcService.AddNewGuard:input_type -> AddNewGuardRequest
	2, // 2: BiliRpcService.RoomCanUseServer:output_type -> google.protobuf.BoolValue
	3, // 3: BiliRpcService.AddNewGuard:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bili_bili_proto_init() }
func file_bili_bili_proto_init() {
	if File_bili_bili_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bili_bili_proto_rawDesc), len(file_bili_bili_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bili_bili_proto_goTypes,
		DependencyIndexes: file_bili_bili_proto_depIdxs,
		MessageInfos:      file_bili_bili_proto_msgTypes,
	}.Build()
	File_bili_bili_proto = out.File
	file_bili_bili_proto_goTypes = nil
	file_bili_bili_proto_depIdxs = nil
}
